{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-root
  labels: {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.rootUser | b64enc | quote }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
  keyfile: {{ randAlphaNum 756 | b64enc | quote }}
{{- end }}
