apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://github.com/CHANGE_ME/devops-assignment
    targetRevision: main
    ref: values
  - repoURL: https://github.com/CHANGE_ME/devops-assignment
    targetRevision: main
    path: helm-templates/ingress-nginx-4.11.2
    helm:
      releaseName: ingress-nginx
      valueFiles:
      - $values/helm-overrides/ingress-nginx/custom-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
