apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://github.com/varnasi2001/devops-assignment
    targetRevision: main
    ref: values
  - repoURL: https://github.com/varnasi2001/devops-assignment
    targetRevision: main
    path: helm-templates/kube-prometheus-stack-62.6.0
    helm:
      releaseName: kps
      valueFiles:
      - $values/helm-overrides/kube-prometheus-stack/custom-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
